INSERT INTO public.registro_de_campo (imovel_numero, imovel_lado, imovel_categoria_da_localidade, imovel_tipo, imovel_status, imovel_complemento, formulario_tipo, li, pe, t, df, pve, numero_da_amostra, quantiade_tubitos, observacao, area_de_visita_id, agente_id, deposito_id, ciclo_id) VALUES
-- ====================================================================================================
-- CICLO 1: 16 inspecionado, 12 fechados, 4 Recusados, 8 Bloqueado/Tratamento
-- ====================================================================================================
(101, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa A', 'Dengue', false, false, true, true, false, NULL, NULL, 'Foco encontrado em prato de planta.', 1, 1, 1, 1),
(102, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Nenhum foco encontrado.', 1, 11, 2, 1),
(103, 'Ímpar', 'Urbana', 'Comércio', 'fechados', 'Loja 3', NULL, false, false, false, false, false, NULL, NULL, 'Estabelecimento fechado.', 1, 1, 3, 1),
(104, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Morador orientado.', 1, 11, 4, 1),
(201, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 02', 'Dengue', false, true, false, false, false, NULL, NULL, 'Nenhum foco encontrado.', 2, 2, 5, 1),
(202, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Caixa d''água destampada.', 2, 3, 6, 1),
(203, 'Ímpar', 'Urbana', 'Residência', 'Recusados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador não permitiu a entrada.', 2, 7, 7, 1),
(204, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Oficina', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Local inspecionado, sem larvas.', 2, 12, 8, 1),
(301, 'Ímpar', 'Urbana', 'Residência', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador ausente.', 3, 4, 9, 1),
(302, 'Par', 'Urbana', 'Residência', 'bloqueado', 'Apto 101', 'Dengue', true, false, true, true, true, 'A001', 2, 'Amostra coletada de ralo e local tratado.', 3, 13, 10, 1),
(303, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Sem focos.', 3, 4, 11, 1),
(304, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Borracharia', 'Dengue', false, true, false, false, false, NULL, NULL, 'Pneus armazenados corretamente.', 3, 13, 12, 1),
(401, 'Ímpar', 'Urbana', 'Terreno Baldio', 'bloqueado', NULL, 'Zica', false, true, true, true, true, NULL, NULL, 'Limpeza e tratamento de focos em pneus.', 4, 5, 13, 1),
(402, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Nenhum foco encontrado.', 4, 9, 14, 1),
(403, 'Ímpar', 'Urbana', 'Comércio', 'fechados', 'Supermercado', NULL, false, false, false, false, false, NULL, NULL, 'Fechado para balanço.', 4, 14, 15, 1),
(404, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Ok.', 4, 5, 16, 1),
(501, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', true, false, false, true, false, 'A002', 1, 'Coleta de amostra positiva.', 5, 1, 17, 1),
(502, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Murado', 'Dengue', false, true, true, false, false, NULL, NULL, 'Tratamento com larvicida granulado.', 5, 7, 18, 1),
(503, 'Ímpar', 'Urbana', 'Residência', 'Recusados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador não permitiu a entrada.', 5, 15, 19, 1),
(504, 'Par', 'Urbana', 'Outros', 'inspecionado', 'Posto de Saúde', 'Zica', false, true, false, false, false, NULL, NULL, 'Inspeção de rotina, sem focos.', 5, 15, 20, 1),
(601, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Apto 202', 'Zica', false, false, false, false, false, NULL, NULL, 'Sem focos.', 6, 8, 21, 1),
(602, 'Par', 'Urbana', 'Residência', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém atendeu.', 6, 16, 22, 1),
(603, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa com piscina', 'Dengue', false, false, true, true, false, NULL, NULL, 'Piscina tratada com larvicida.', 6, 15, 23, 1),
(604, 'Par', 'Urbana', 'Comércio', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Comércio fechado permanentemente.', 6, 16, 24, 1),
(701, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Restaurante', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Sem focos na área externa.', 7, 9, 25, 1),
(702, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Casa dos Fundos', 'Chikungunya', false, false, true, true, false, NULL, NULL, 'Foco em balde, tratado.', 7, 16, 26, 1),
(703, 'Ímpar', 'Urbana', 'Comércio', 'fechados', 'Clínica', NULL, false, false, false, false, false, NULL, NULL, 'Fechado, horário de almoço.', 7, 15, 27, 1),
(704, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Morador orientado sobre prevenção.', 7, 16, 28, 1),
(801, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ambiente limpo e sem depósitos.', 8, 11, 29, 1),
(802, 'Par', 'Urbana', 'Residência', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Cachorro bravo, morador ausente.', 8, 16, 30, 1),
(803, 'Ímpar', 'Urbana', 'Residência', 'bloqueado', 'Cond. Fechado', 'Chikungunya', false, false, true, true, true, NULL, NULL, 'Foco em área comum do condomínio.', 8, 11, 31, 1),
(804, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 8, 16, 32, 1),
(901, 'Ímpar', 'Urbana', 'Outros', 'inspecionado', 'Escola', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 9, 1, 33, 1),
(902, 'Par', 'Urbana', 'Residência', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém em casa.', 9, 12, 34, 1),
(903, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Aberto', 'Chikungunya', false, true, false, true, false, NULL, NULL, 'Encontrado lixo com água, eliminado mecanicamente.', 9, 1, 35, 1),
(904, 'Par', 'Urbana', 'Residência', 'Recusados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador informou que não recebe visitas.', 9, 12, 36, 1),
(1001, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Bloco B Apto 1002', 'Zica', false, false, false, true, false, NULL, NULL, 'Foco em bromélia na varanda, eliminado.', 10, 13, 37, 1),
(1002, 'Par', 'Urbana', 'Residência', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém atendeu.', 10, 16, 38, 1),
(1003, 'Ímpar', 'Urbana', 'Residência', 'Recusados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 10, 13, 39, 1),
(1004, 'Par', 'Urbana', 'Terreno Baldio', 'fechados', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Portão trancado.', 10, 16, 40, 1),
(101, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa A', 'Dengue', false, false, false, false, false, NULL, NULL, 'Revisita. Local limpo.', 1, 1, 41, 2),
(102, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Novo foco em garrafa no quintal.', 1, 11, 42, 2),
(103, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 3', 'Dengue', false, true, false, false, false, NULL, NULL, 'Estabelecimento aberto, tudo ok.', 1, 1, 43, 2),
(104, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Calha limpa, sem água acumulada.', 1, 11, 44, 2),
(201, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 02', 'Dengue', false, true, false, false, false, NULL, NULL, 'Segunda visita, tudo ok.', 2, 2, 45, 2),
(202, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Caixa d''água agora está tampada.', 2, 3, 46, 2),
(203, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Morador permitiu entrada. Sem focos.', 2, 7, 47, 2),
(204, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Oficina', 'Dengue', false, true, false, false, false, NULL, NULL, 'Inspeção de rotina, ok.', 2, 12, 48, 2),
(301, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Morador encontrado. Casa inspecionada.', 3, 4, 49, 2),
(302, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Apto 101', 'Zica', false, false, false, false, false, NULL, NULL, 'Revisita, sem necessidade de nova amostra.', 3, 13, 50, 2),
(303, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Pequeno foco em vaso de planta. Tratado.', 3, 4, 51, 2),
(304, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Borracharia', 'Dengue', false, true, false, false, false, NULL, NULL, 'Pneus permanecem secos e cobertos.', 3, 13, 52, 2),
(401, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', NULL, 'Zica', false, true, false, false, false, NULL, NULL, 'Terreno permanece limpo.', 4, 5, 53, 2),
(402, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 4, 9, 54, 2),
(403, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Supermercado', 'Dengue', false, true, false, false, false, NULL, NULL, 'Sem alterações.', 4, 14, 55, 2),
(404, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador em viagem.', 4, 5, 56, 2),
(501, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Revisita de acompanhamento, sem larvas.', 5, 1, 57, 2),
(502, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Murado', 'Dengue', false, true, false, false, false, NULL, NULL, 'Sem novos focos.', 5, 7, 58, 2),
(503, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador continua recusando a visita.', 5, 15, 59, 2),
(504, 'Par', 'Urbana', 'Outros', 'inspecionado', 'Posto de Saúde', 'Zica', false, true, false, false, false, NULL, NULL, 'Inspeção de rotina, tudo ok.', 5, 15, 60, 2),
(601, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Apto 202', 'Zica', false, false, false, false, false, NULL, NULL, 'Ok.', 6, 8, 61, 2),
(602, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Sem alterações.', 6, 16, 62, 2),
(603, 'Ímpar', 'Urbana', 'Residência', 'bloqueado', NULL, 'Dengue', false, false, true, true, true, NULL, NULL, 'Piscina com água parada. Tratada.', 6, 15, 63, 2),
(604, 'Par', 'Urbana', 'Comércio', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Comércio fechado permanentemente.', 6, 16, 64, 2),
(701, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Restaurante', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Revisita, local limpo.', 7, 9, 65, 2),
(702, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Casa dos Fundos', 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Sem novos focos.', 7, 16, 66, 2),
(703, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Clínica', 'Dengue', false, true, true, true, false, NULL, NULL, 'Foco em ralo externo. Tratado.', 7, 15, 67, 2),
(704, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 7, 16, 68, 2),
(801, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém atendeu.', 8, 11, 69, 2),
(802, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém em casa.', 8, 16, 70, 2),
(803, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Cond. Fechado', 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Área comum permanece limpa.', 8, 11, 71, 2),
(804, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Lixo acumulado no quintal com água.', 8, 16, 72, 2),
(901, 'Ímpar', 'Urbana', 'Outros', 'inspecionado', 'Escola', 'Dengue', false, true, false, false, false, NULL, NULL, 'Inspeção de rotina, sem focos.', 9, 1, 73, 2),
(902, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Ok.', 9, 12, 74, 2),
(903, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Aberto', 'Chikungunya', false, true, true, true, false, NULL, NULL, 'Novo acúmulo de lixo com água.', 9, 1, 75, 2),
(904, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa persistente.', 9, 12, 76, 2),
(1001, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Bloco B Apto 1002', 'Zica', false, false, false, false, false, NULL, NULL, 'Sem novos focos.', 10, 13, 77, 2),
(1002, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Morador encontrado. Casa inspecionada.', 10, 16, 78, 2),
(1003, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 10, 13, 79, 2),
(1004, 'Par', 'Urbana', 'Terreno Baldio', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Acesso bloqueado.', 10, 16, 80, 2),
(101, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa A', 'Dengue', false, false, false, false, false, NULL, NULL, 'Terceira visita de rotina. Sem alterações.', 1, 1, 81, 3),
(102, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Revisita. Local permanece limpo.', 1, 11, 82, 3),
(103, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 3', 'Dengue', false, true, false, false, false, NULL, NULL, 'Estabelecimento aberto. inspecionado, ok.', 1, 1, 83, 3),
(104, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Tudo certo.', 1, 11, 84, 3),
(201, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 02', 'Dengue', false, true, true, true, false, NULL, NULL, 'Pequeno foco em ralo dos fundos.', 2, 2, 85, 3),
(202, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 2, 3, 86, 3),
(203, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Sem alterações.', 2, 7, 87, 3),
(204, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Oficina', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Terceira inspeção. Sem irregularidades.', 2, 12, 88, 3),
(301, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Sem focos.', 3, 4, 89, 3),
(302, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Apto 101', 'Dengue', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 3, 13, 90, 3),
(303, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Sem alterações.', 3, 4, 91, 3),
(304, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Borracharia', 'Dengue', false, true, false, false, false, NULL, NULL, 'Tudo certo.', 3, 13, 92, 3),
(401, 'Ímpar', 'Urbana', 'Terreno Baldio', 'bloqueado', NULL, 'Zica', false, true, true, true, true, NULL, NULL, 'Novo descarte irregular de lixo.', 4, 5, 93, 3),
(402, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Ok.', 4, 9, 94, 3),
(403, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Supermercado', 'Dengue', false, true, true, true, false, NULL, NULL, 'Foco na área dos carrinhos.', 4, 14, 95, 3),
(404, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Morador presente, tudo ok.', 4, 5, 96, 3),
(501, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Foco em pneu velho no quintal.', 5, 1, 97, 3),
(502, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Murado', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 5, 7, 98, 3),
(503, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 5, 15, 99, 3),
(504, 'Par', 'Urbana', 'Outros', 'inspecionado', 'Posto de Saúde', 'Zica', false, true, false, false, false, NULL, NULL, 'Ok.', 5, 15, 100, 3),
(601, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Apto 202', 'Zica', false, false, true, true, false, NULL, NULL, 'Foco em vaso de planta na sacada.', 6, 8, 101, 3),
(602, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 6, 16, 102, 3),
(603, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa com piscina', 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 6, 15, 103, 3),
(604, 'Par', 'Urbana', 'Comércio', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Comércio fechado permanentemente.', 6, 16, 104, 3),
(701, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Restaurante', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Ok.', 7, 9, 105, 3),
(702, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, true, true, false, NULL, NULL, 'Foco em tambor de água.', 7, 16, 106, 3),
(703, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Clínica', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 7, 15, 107, 3),
(704, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, false, false, NULL, NULL, 'Pequeno foco em brinquedo no quintal.', 7, 16, 108, 3),
(801, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 8, 11, 109, 3),
(802, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Morador encontrado. Tudo certo.', 8, 16, 110, 3),
(803, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Cond. Fechado', 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Ok.', 8, 11, 111, 3),
(804, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 8, 16, 112, 3),
(901, 'Ímpar', 'Urbana', 'Outros', 'bloqueado', 'Escola', 'Dengue', false, true, true, true, true, NULL, NULL, 'Início do período letivo, tratamento preventivo.', 9, 1, 113, 3),
(902, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, true, true, false, NULL, NULL, 'Foco em ralo.', 9, 12, 114, 3),
(903, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Aberto', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Terreno permanece limpo.', 9, 1, 115, 3),
(904, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 9, 12, 116, 3),
(1001, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Bloco B Apto 1002', 'Zica', false, false, false, false, false, NULL, NULL, 'Ok.', 10, 13, 117, 3),
(1002, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém atendeu novamente.', 10, 16, 118, 3),
(1003, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 10, 13, 119, 3),
(1004, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', NULL, 'Zica', false, true, false, false, false, NULL, NULL, 'Ok.', 10, 16, 120, 3),
(101, 'Ímpar', 'Urbana', 'Residência', 'bloqueado', 'Casa A', 'Zica', false, false, true, true, true, NULL, NULL, 'Visita de Zica, foco encontrado na calha.', 1, 1, 121, 4),
(102, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Local limpo.', 1, 11, 122, 4),
(103, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 3', 'Dengue', false, true, false, false, false, NULL, NULL, 'Tudo ok.', 1, 1, 123, 4),
(104, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Ok.', 1, 11, 124, 4),
(201, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Loja 02', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 2, 2, 125, 4),
(202, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 2, 3, 126, 4),
(203, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Morador não estava em casa na 4a visita.', 2, 7, 127, 4),
(204, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Oficina', 'Chikungunya', false, true, false, false, false, NULL, NULL, 'Ok.', 2, 12, 128, 4),
(301, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Visita de rotina, ok.', 3, 4, 129, 4),
(302, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Apto 101', 'Dengue', true, false, true, true, false, NULL, NULL, 'Foco recorrente em ralo. Tratado.', 3, 13, 130, 4),
(303, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 3, 4, 131, 4),
(304, 'Par', 'Urbana', 'Comércio', 'inspecionado', 'Borracharia', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 3, 13, 132, 4),
(401, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', NULL, 'Zica', false, true, false, false, false, NULL, NULL, 'Terreno limpo.', 4, 5, 133, 4),
(402, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, true, true, false, NULL, NULL, 'Foco em pneu de enfeite no jardim.', 4, 9, 134, 4),
(403, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Supermercado', 'Dengue', false, true, false, false, false, NULL, NULL, 'Ok.', 4, 14, 135, 4),
(404, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Ok.', 4, 5, 136, 4),
(501, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Água acumulada em laje. Tratado.', 5, 1, 137, 4),
(502, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Murado', 'Dengue', false, true, true, false, false, NULL, NULL, 'Novo foco de lixo.', 5, 7, 138, 4),
(503, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 5, 15, 139, 4),
(504, 'Par', 'Urbana', 'Outros', 'inspecionado', 'Posto de Saúde', 'Zica', false, true, false, false, false, NULL, NULL, 'Ok.', 5, 15, 140, 4),
(601, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Apto 202', 'Zica', false, false, false, false, false, NULL, NULL, 'Ok.', 6, 8, 141, 4),
(602, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Ok.', 6, 16, 142, 4),
(603, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Casa com piscina', 'Dengue', false, false, false, false, false, NULL, NULL, 'Piscina ok.', 6, 15, 143, 4),
(604, 'Par', 'Urbana', 'Comércio', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Comércio fechado permanentemente.', 6, 16, 144, 4),
(701, 'Ímpar', 'Urbana', 'Comércio', 'bloqueado', 'Restaurante', 'Chikungunya', false, true, true, true, true, NULL, NULL, 'Foco em tambor nos fundos.', 7, 9, 145, 4),
(702, 'Par', 'Urbana', 'Residência', 'inspecionado', 'Casa dos Fundos', 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 7, 16, 146, 4),
(703, 'Ímpar', 'Urbana', 'Comércio', 'inspecionado', 'Clínica', 'Dengue', false, true, false, false, false, NULL, NULL, 'Tudo ok.', 7, 15, 147, 4),
(704, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Foco em caixa d''água no telhado.', 7, 16, 148, 4),
(801, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, true, true, false, NULL, NULL, 'Foco em ralo.', 8, 11, 149, 4),
(802, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Zica', false, false, false, false, false, NULL, NULL, 'Morador presente, tudo certo.', 8, 16, 150, 4),
(803, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Cond. Fechado', 'Chikungunya', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 8, 11, 151, 4),
(804, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 8, 16, 152, 4),
(901, 'Ímpar', 'Urbana', 'Outros', 'inspecionado', 'Escola', 'Dengue', false, true, false, false, false, NULL, NULL, 'Tudo ok.', 9, 1, 153, 4),
(902, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Ninguém em casa.', 9, 12, 154, 4),
(903, 'Ímpar', 'Urbana', 'Terreno Baldio', 'inspecionado', 'Aberto', 'Chikungunya', false, true, true, true, false, NULL, NULL, 'Foco em entulho.', 9, 1, 155, 4),
(904, 'Par', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 9, 12, 156, 4),
(1001, 'Ímpar', 'Urbana', 'Residência', 'inspecionado', 'Bloco B Apto 1002', 'Zica', false, false, false, false, false, NULL, NULL, 'Tudo ok.', 10, 13, 157, 4),
(1002, 'Par', 'Urbana', 'Residência', 'inspecionado', NULL, 'Dengue', false, false, false, false, false, NULL, NULL, 'Morador atendeu. Ok.', 10, 16, 158, 4),
(1003, 'Ímpar', 'Urbana', 'Residência', 'nao_inspecionado', NULL, NULL, false, false, false, false, false, NULL, NULL, 'Recusa.', 10, 13, 159, 4),
(1004, 'Par', 'Urbana', 'Terreno Baldio', 'inspecionado', NULL, 'Zica', false, true, true, true, false, NULL, NULL, 'Água parada em lona. Tratado.', 10, 16, 160, 4);
